import Head from 'next/head';
import HomeView from '@/views/home/HomeView';
import { statusIsAuth } from '@/api';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { Container } from '@mui/material';
const Home = () => {
  const { push } = useRouter();

  useEffect(() => {
    !statusIsAuth && push('/logout');
  }, [push]);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <HomeView />
      </Container>
    </>
  );
};

export default Home;
