import Head from 'next/head';
import HomeView from '@/views/home/HomeView';
import Menu from '../components/menu/Menu';
import { Container } from '@mui/material';

const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ display: 'flex' }}>
        <Menu />
        <HomeView />
      </Container>
    </>
  );
};

export default Home;
