import Head from 'next/head';
import { Container } from '@mui/material';
import Registration from '@/views/registration/Registration';

const Home = () => {
  return (
    <>
      <Head>
        <title>Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}
      >
        <Registration />
      </Container>
    </>
  );
};

export default Home;
